name: List
on:
  workflow_call:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java-gradle

      - name: Run lintRelease
        run: ./gradlew lintRelease

      - uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: build/reports/lint/lint-result.sarif
          category: lintRelease
